<?xml version="1.0"?>
<robot xmlns:xacro="http:/www.ros.org/wiki/xacro" name="my_robot">

    <material name="grey">
        <color rgba="0.5 0.5 0.5 1"/>
    </material>

    <material name="blue">
        <color rgba="0 0 0.6 1"/>
    </material>

    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>

    <xacro:property name="base_length" value="1"/>
    <xacro:property name="base_width" value="0.6"/>
    <xacro:property name="base_height" value="0.4"/>
    <xacro:property name="base_mass" value="10"/>
    <xacro:property name="stand_height" value="0.3"/>
    <xacro:property name="stand_length" value="0.15"/>
    <xacro:property name="stand_width" value="0.45"/>
    <xacro:property name="stand_mass" value="3"/>
    <xacro:property name="wheel_radius" value="0.2"/>
    <xacro:property name="wheel_length" value="0.1"/>
    <xacro:property name="wheel_mass" value="2.5"/>
    <xacro:property name="camera_height" value="0.1"/>
    <xacro:property name="camera_length" value="0.1"/>
    <xacro:property name="camera_width" value="0.1"/>
    <xacro:property name="camera_mass" value="0.1"/>

    <xacro:include filename="$(find rover)/models/rover.gazebo"/>

    <joint name="stand_joint" type="fixed">
        <origin xyz="${2*base_length/7} 0 ${wheel_radius * 0.8 + base_height + stand_height/2}"/>
        <parent link="base_link"/>
        <child link="stand_link"/>
    </joint>

    <!-- <joint name="camera_l_joint" type="fixed">
        <origin xyz="${stand_length/2} ${stand_width/3} ${stand_height/2 - camera_height/2}"/>
        <parent link="stand_link"/>
        <child link="camera_l_link"/>
    </joint>

    <joint name="camera_r_joint" type="fixed">
        <origin xyz="${stand_length/2} ${-stand_width/3} ${stand_height/2 - camera_height/2}"/>
        <parent link="stand_link"/>
        <child link="camera_r_link"/>
    </joint> -->

    <joint name="lidar_joint" type="fixed">
        <origin xyz="0 0 ${stand_height/2 + camera_height/2}"/>
        <parent link="stand_link"/>
        <child link="lidar_link"/>
    </joint>

    <joint name="wheel_fr_joint" type="continuous">
        <parent link="base_link"/>
        <child link="wheel_fr_link"/>
        <axis xyz="0 1 0"/>
        <origin xyz="${2*base_length/7} ${-base_width/2 - wheel_length/2} ${wheel_radius}" rpy="0 0 0"/>
        <limit effort="20000" velocity="1"/>
        <dynamics damping="1.0" friction="1.0"/>
    </joint>

    <joint name="wheel_fl_joint" type="continuous">
        <parent link="base_link"/>
        <child link="wheel_fl_link"/>
        <axis xyz="0 1 0"/>
        <origin xyz="${2*base_length/7} ${base_width/2 + wheel_length/2} ${wheel_radius}" rpy="0 0 0"/>
        <limit effort="20000" velocity="1"/>
        <dynamics damping="1.0" friction="1.0"/>
    </joint>

    <joint name="wheel_br_joint" type="continuous">
        <parent link="base_link"/>
        <child link="wheel_br_link"/>
        <axis xyz="0 1 0"/>
        <origin xyz="${-2*base_length/7} ${-base_width/2 - wheel_length/2} ${wheel_radius}" rpy="0 0 0"/>
        <limit effort="20000" velocity="1"/>
        <dynamics damping="1.0" friction="1.0"/>
    </joint>

    <joint name="wheel_bl_joint" type="continuous">
        <parent link="base_link"/>
        <child link="wheel_bl_link"/>
        <axis xyz="0 1 0"/>
        <origin xyz="${-2*base_length/7} ${base_width/2 + wheel_length/2} ${wheel_radius}" rpy="0 0 0"/>
        <limit effort="20000" velocity="1"/>
        <dynamics damping="1.0" friction="1.0"/>
    </joint>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${wheel_radius * 0.8 + base_height/2}" rpy="0 0 0"/>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${wheel_radius * 0.8 + base_height/2}" rpy="0 0 0"/>
        </collision>
        <inertial>
            <origin xyz="0 0 ${wheel_radius * 0.8 + base_height/2}" rpy="0 0 0"/>
            <mass value="${base_mass}"/>
            <inertia ixx="${(base_mass/12)*(base_height * base_height + base_length * base_length)}" ixy="0" ixz="0" iyy="${(base_mass/12)*(base_height * base_height + base_width * base_width)}" iyz="0" izz="${(base_mass/12)*(base_length * base_length + base_width * base_width)}"/>
        </inertial>
    </link>

    <link name="stand_link">
        <visual>
            <geometry>
                <box size="${stand_length} ${stand_width} ${stand_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <box size="${stand_length} ${stand_width} ${stand_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${stand_mass}"/>
            <inertia ixx="${(stand_mass/12)*(stand_height * stand_height + stand_length * stand_length)}" ixy="0" ixz="0" iyy="${(stand_mass/12)*(stand_height * stand_height + stand_width * stand_width)}" iyz="0" izz="${(stand_mass/12)*(stand_length * stand_length + stand_width * stand_width)}"/>
        </inertial>
    </link>

    <!-- <link name="camera_l_link">
        <visual>
            <geometry>
                <box size="${camera_length/2} ${camera_width} ${camera_height}"/>
            </geometry>
            <origin xyz="${-camera_length/4 + camera_length/2} 0 0" rpy="0 0 0"/>
            <material name="white"/>
        </visual>
        <visual>
            <geometry>
                <cylinder radius="${camera_width/3.2}" length="${camera_length/2}"/>
            </geometry>
            <origin xyz="${camera_length/4 + camera_length/2} 0 0" rpy="0 ${pi/2} 0"/>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${camera_mass}"/>
            <inertia ixx="${(camera_mass/12)*(camera_height * camera_height + camera_length * camera_length)}" ixy="0" ixz="0" iyy="${(camera_mass/12)*(camera_height * camera_height + camera_width * camera_width)}" iyz="0" izz="${(camera_mass/12)*(camera_length * camera_length + camera_width * camera_width)}"/>
        </inertial>
    </link>

    <link name="camera_r_link">
        <visual>
            <geometry>
                <box size="${camera_length/2} ${camera_width} ${camera_height}"/>
            </geometry>
            <origin xyz="${-camera_length/4 + camera_length/2} 0 0" rpy="0 0 0"/>
            <material name="white"/>
        </visual>
        <visual>
            <geometry>
                <cylinder radius="${camera_width/3.2}" length="${camera_length/2}"/>
            </geometry>
            <origin xyz="${camera_length/4 + camera_length/2} 0 0" rpy="0 ${pi/2} 0"/>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${camera_mass}"/>
            <inertia ixx="${(camera_mass/12)*(camera_height * camera_height + camera_length * camera_length)}" ixy="0" ixz="0" iyy="${(camera_mass/12)*(camera_height * camera_height + camera_width * camera_width)}" iyz="0" izz="${(camera_mass/12)*(camera_length * camera_length + camera_width * camera_width)}"/>
        </inertial>
    </link> -->

    <link name="lidar_link">
        <visual>
            <geometry>
                <cylinder radius="${camera_width/2}" length="${camera_length}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${camera_width/2}" length="${camera_length}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${camera_mass}"/>
            <inertia ixx="${(camera_mass/12)*(3 * camera_width/2 * camera_width/2 + camera_length * camera_length)}" ixy="0" ixz="0" iyy="${(camera_mass/12)*(3 * camera_width/2 * camera_width/2 + camera_length * camera_length)}" iyz="0" izz="${(camera_mass * camera_width/2 * camera_width/2) / 2}"/>
        </inertial>
    </link>

    <link name="wheel_fr_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            <material name="grey"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            <mass value="${wheel_mass}"/>
            <inertia ixx="${(wheel_mass/12)*(3 * wheel_radius * wheel_radius + wheel_length * wheel_length)}" ixy="0" ixz="0" iyy="${(wheel_mass/12)*(3 * wheel_radius * wheel_radius + wheel_length * wheel_length)}" iyz="0" izz="${(wheel_mass * wheel_radius * wheel_radius) / 2}"/>
        </inertial>
    </link>

    <link name="wheel_fl_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            <material name="grey"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            <mass value="${wheel_mass}"/>
            <inertia ixx="${(wheel_mass/12)*(3 * wheel_radius * wheel_radius + wheel_length * wheel_length)}" ixy="0" ixz="0" iyy="${(wheel_mass/12)*(3 * wheel_radius * wheel_radius + wheel_length * wheel_length)}" iyz="0" izz="${(wheel_mass * wheel_radius * wheel_radius) / 2}"/>
        </inertial>
    </link>

    <link name="wheel_br_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            <material name="grey"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            <mass value="${wheel_mass}"/>
            <inertia ixx="${(wheel_mass/12)*(3 * wheel_radius * wheel_radius + wheel_length * wheel_length)}" ixy="0" ixz="0" iyy="${(wheel_mass/12)*(3 * wheel_radius * wheel_radius + wheel_length * wheel_length)}" iyz="0" izz="${(wheel_mass * wheel_radius * wheel_radius) / 2}"/>
        </inertial>
    </link>

    <link name="wheel_bl_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            <material name="grey"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            <mass value="${wheel_mass}"/>
            <inertia ixx="${(wheel_mass/12)*(3 * wheel_radius * wheel_radius + wheel_length * wheel_length)}" ixy="0" ixz="0" iyy="${(wheel_mass/12)*(3 * wheel_radius * wheel_radius + wheel_length * wheel_length)}" iyz="0" izz="${(wheel_mass * wheel_radius * wheel_radius) / 2}"/>
        </inertial>
    </link>

</robot>
